### ISSUE TITLE
Screenshot in README not shown on themes.gohugo.io

### ISSUE THREAD

**Issue by digitalcraftsman** [diwao/hestia-pure#1]
Hi @diwao,

the README of this repo is also displayed on [www.themes.gohugo.io](https://themes.gohugo.io/hestia-pure/). The screenshot in the README isn't shown because the file was linked with a relative path and the directory tree on the server differs from that on Github.

Just make sure you use an [absolute path to the screenshot](https://github.com/gohugoio/hugoThemes#readmemd) to circumvent this-

**Comment by diwao** [comment]
Hi @digitalcraftsman,

Thank you for the report. I have fixed the file path of screenshot in the [REAEME](https://github.com/diwao/hestia-pure/blob/master/README.md).
